baseURL = "https://financial-controller-oceans-61680.netlify.com/"

languageCode = "en-us"

title = "Min nya sida"
 
theme = "ananke"

SectionPagesMenu = "main"

[params]
  twitter = "https://twitter.com/t4ostra"
  featured_image = "/images/hero-image.jpg"
